= devops-stack-module-application

A https://devops-stack.io[DevOps Stack] module to deploy a simple Application in Argo CD.

The module creates an Argo CD AppProject using the name given on declaration and then creates an Argo CD Application using the chart that is inside the path for the Git repository that is declared.

Inside that folder, the module expects an Helm chart with a folder structure similar to the following (as is standard practice):

....
application_folder
  ├── Chart.yaml
  ├── charts
  │   ├── dependency1.tar.gz
  │   └── dependency2.tar.gz
  ├── secrets.yaml
  ├── templates
  │   ├── template1.yaml
  │   ├── template2.yaml
  │   ├── template3.yaml
  │   └── _helpers.tpl
  └── values.yaml
....

By default, the created AppProject can only create an Application within a Namespace of the same name or within a Namespace declared on the module declaration. Besides that, the AppProject has the permission to create any kind of Kubernetes resources inside the destination cluster, but you can restrict the allowed resources if you need to.

== Usage

This module can be declared by adding the following block on your Terraform configuration:

[source,hcl]
----
module "module_name" {
  source = "git::https://github.com/camptocamp/devops-stack-module-application.git?ref=<RELEASE>"

  name = "application-name"
  argocd_namespace = local.argocd_namespace

  source_repo = "https://github.com/owner/repository.git"
  source_repo_path = "path/to/chart"
  source_target_revision = "branch"

  depends_on = [module.argocd]
}
----

A more complex declaration, that defines the Namespace and also the AppProject allowed resources, would look like this:

[source,hcl]
----
module "module_name" {
  source = "git::https://github.com/camptocamp/devops-stack-module-application.git?ref=<RELEASE>"

  name = "application-name"
  argocd_namespace = local.argocd_namespace

  source_repo = "https://github.com/owner/repository.git"
  source_repo_path = "path/to/chart"
  source_target_revision = "branch"

  destination_namespace = "namespace"

  project_cluster_resource_whitelist = [ 
    {
      group = "*"
      kind = "Namespace"
    },
  ]

  project_namespace_resource_whitelist = [
    {
      group = "apps"
      kind = "Deployment"
    },
    {
      group = "*"
      kind = "Service"
    },
  ]

  depends_on = [module.argocd]
}
----

Furthermore, you can customize the chart's `values.yaml` by adding an Helm configuration as an HCL structure:

[source,hcl]
----
module "module_name" {
  source = "git::https://github.com/camptocamp/devops-stack-module-application.git?ref=<RELEASE>"

  name = "application-name"
  argocd_namespace = local.argocd_namespace

  source_repo = "https://github.com/owner/repository.git"
  source_repo_path = "path/to/chart"
  source_target_revision = "branch"

  helm_values = [
    map = {
      string = "string"
      bool = true
    }
    sequence = [
      {
        key1 = "value1"
        key2 = "value2"
      },
      {
        key1 = "value1"
        key2 = "value2"
      },
    ]
    sequence2 = [
      "string1",
      "string2"
    ]
  ]
  
  depends_on = [module.argocd]
}
----

== Technical Reference

=== Dependencies

==== `module.argocd`

As this is an application, it needs to be deployed after the deployment of Argo CD and consequently this module needs to have this explicit dependency.

include::tf_docs.adoc[leveloffset=+2]
