<!-- BEGIN_TF_DOCS -->
= Requirements

No requirements.

= Providers

The following providers are used by this module:

- [[provider_argocd]] <<provider_argocd,argocd>>

- [[provider_null]] <<provider_null,null>>

- [[provider_utils]] <<provider_utils,utils>>

= Modules

No modules.

= Resources

The following resources are used by this module:

- https://registry.terraform.io/providers/oboukili/argocd/latest/docs/resources/application[argocd_application.this] (resource)
- https://registry.terraform.io/providers/oboukili/argocd/latest/docs/resources/project[argocd_project.this] (resource)
- https://registry.terraform.io/providers/hashicorp/null/latest/docs/resources/resource[null_resource.this] (resource)
- https://registry.terraform.io/providers/cloudposse/utils/latest/docs/data-sources/deep_merge_yaml[utils_deep_merge_yaml.values] (data source)

= Required Inputs

The following input variables are required:

== [[input_argocd_namespace]] <<input_argocd_namespace,argocd_namespace>>

Description: n/a

Type: `string`

== [[input_name]] <<input_name,name>>

Description: Name to give the to the AppProject and Application.

Type: `string`

== [[input_source_repo]] <<input_source_repo,source_repo>>

Description: Repository where the application's chart is located.

Type: `string`

== [[input_source_repo_path]] <<input_source_repo_path,source_repo_path>>

Description: Path for the application's chart in the source repository.

Type: `string`

== [[input_source_target_revision]] <<input_source_target_revision,source_target_revision>>

Description: Git target revision for the application.

Type: `string`

= Optional Inputs

The following input variables are optional (have default values):

== [[input_dependency_ids]] <<input_dependency_ids,dependency_ids>>

Description: n/a

Type: `map(string)`

Default: `{}`

== [[input_destination_namespace]] <<input_destination_namespace,destination_namespace>>

Description: Namespace where the application will be deployed. By default it is the same as the application's name defined by `var.name`. We use a ternary operator to conditionally define the Namespace only if it is defined on the module's instantiation: `namespace = var.destination_namespace == null ? var.name : var.destination_namespace`.

Type: `string`

Default: `null`

== [[input_helm_values]] <<input_helm_values,helm_values>>

Description: Helm values, passed as a list of HCL structures.

Type: `any`

Default: `[]`

== [[input_project_cluster_resource_whitelist]] <<input_project_cluster_resource_whitelist,project_cluster_resource_whitelist>>

Description: Cluster-scoped resources allowed to be deployed in the Argo CD AppProject created by the module. The **`group`** must be a Kubernetes API group such as `core` or `apps` and the **`kind`** must be a Kubernetes Kinds/Object Schemas such as `Namespace` or `ClusterRole` (note that only resources like these ones are compatible with this setting, the other resources are only Namespace-scoped). You can see the API Groups [here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#-strong-api-groups-strong-).

Type:
[source,hcl]
----
list(object({
    group = string
    kind = string
  }))
----

Default:
[source,json]
----
[
  {
    "group": "*",
    "kind": "*"
  }
]
----

== [[input_project_namespace_resource_whitelist]] <<input_project_namespace_resource_whitelist,project_namespace_resource_whitelist>>

Description: Namespace-scoped resources allowed to be deployed in the Argo CD AppProject created by the module. The **`group`** must be a Kubernetes API group such as `core` or `apps` and the **`kind`** must be a Kubernetes Kinds/Object Schemas such as `Pod`, `ConfigMap`, `DaemonSet`, `Deployment`, etc. You can see the API Groups [here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#-strong-api-groups-strong-).

Type:
[source,hcl]
----
list(object({
    group = string
    kind = string
  }))
----

Default:
[source,json]
----
[
  {
    "group": "*",
    "kind": "*"
  }
]
----

= Outputs

The following outputs are exported:

== [[output_id]] <<output_id,id>>

Description: n/a
<!-- END_TF_DOCS -->